# Generated by Django 6.1.1 on 2026-09-04 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='coursematerial',
            old_name='des',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='ins_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='ins_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='pro_img',
            new_name='profile_img',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='image',
            new_name='profile_image',
        ),
    ]
