# Generated by Django 6.1.1 on 2026-09-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_course_name_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('Completed', 'completed'), ('Pending', 'pending')], max_length=20),
        ),
    ]
